normal:
	uv run tart-position-cal     --measurements antenna_measurements.ods     --positions antenna_positions.json     --output na-unam_processed_antenna_positions.json     --rot-index 3     --rot-degrees 18.1125

irls:
	uv run tart-position-cal     --measurements antenna_measurements.ods     --positions antenna_positions.json     --output na-unam_processed_antenna_positions.json     --rot-index 3     --rot-degrees 18.1125 --irls --title irls
